services:
  postgres:
    image: postgres:15
    container_name: ame-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ame-secreto
      - POSTGRES_DB=evolution
    ports:
      - 5432:5432
    volumes:
      - ame_db:/var/lib/postgresql/data
    restart: always

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: ame-n8n
    ports:
      - 5678:5678
    environment:
      - WEBHOOK_URL=https://epeiric-nova-poetastric.ngrok-free.dev
      - GENERIC_TIMEZONE=America/Lima
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

volumes:
  ame_db:
  n8n_data: